var _HTTP_SERVER_IP = "yk-hosted-12-31.ydns.eu"
var _HTTP_SERVER_PORT = "9380"
var HTTP_SERVER_HOST = _HTTP_SERVER_IP + ':' + _HTTP_SERVER_PORT

var _HTTP_FORECAST_API_SERVER_IP = "yk-hosted-12-31.ydns.eu"
var _HTTP_FORECAST_API_SERVER_PORT = "9381"
var HTTP_FORECAST_API_SERVER_HOST = _HTTP_FORECAST_API_SERVER_IP + ':' + _HTTP_FORECAST_API_SERVER_PORT
